### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/ShapeNet/data/ShapeNetTrain/02958343_25f9e0e65b8fae1f9916e41a3ca14d3a_15.dat'

### ISSUE THREAD

**Issue by star-cold** [zouchuhang/Silhouette-Guided-3D#2]
In pixel2mesh the data path is Data/ShapeNetP2M/04256520/cc644fad0b76a441d84c7dc40ac6d743/rendering/00.dat  to  04.dat， but   
your trianing_list there is 00.dat to 23.dat， then where is the extra data from 04 to 23?
best wishes!

**Comment by zouchuhang** [comment]
@star-cold You need to ask the pixel2mesh authors for details. My experiment is based entirely on their data downloaded in January 2019.

**Comment by star-cold** [comment]
> @star-cold You need to ask the pixel2mesh authors for details. My experiment is based entirely on their data downloaded in January 2019.

Thanks a lot!
